resolutionMode: highest
autoInstallPeers: true
strictPeerDependencies: false
shellEmulator: true

packages:
  - 'scripts'
  - 'ts-perf'
  - 'ts-perf/packages/*'

requiredScripts:
  - build

allowBuilds:
  '@esfx/equatable': true
  dprint: true
